services:
  nginx:
    image: nginx:alpine
    container_name: ploszukiwacz-website
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - website-network
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm-alpine
    container_name: ploszukiwacz-php-fpm
    volumes:
      - ./src:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - website-network

networks:
  website-network:
    driver: bridge
