services:
  nginx:
    image: nginx:alpine
    container_name: ${CONTAINER_NAME:-ploszukiwacz-website}
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME:-website-network}

networks:
  ${NETWORK_NAME:-website-network}:
    driver: bridge
